### ISSUE TITLE
Todo for 3.0 release

### ISSUE THREAD

**Issue by poltertec** [solus-project/evopop-gtk-theme#71]
- [] Tweak Budgie menu
- [] Budgie Task List widget shouldn't be bold
- [] Tweak sidebar lists
- [] Fix window styling non GTK
